---
- hosts: localhost
  connection: local
  gather_facts: False
  become: yes

  tasks:
  - name: Gather information about the tag "BuildInstance"
    community.aws.ec2_instance_info:
      filters:
        "tag:Name": BuildInstance
        instance-state-name: [ "running"]
      region: us-east-2
    register: BuildInstance_result

  - name: Gather information about the tag "ProdInstance"
    community.aws.ec2_instance_info:
      filters:
        "tag:Name": ProdInstance
        instance-state-name: [ "running"]
      region: us-east-2
    register: ProdInstance_result

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 5
      timeout: 10
      state: started
    with_items: "{{ BuildInstance_result.instances }}"

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 5
      timeout: 10
      state: started
    with_items: "{{ ProdInstance_result.instances }}"

  - name: Add public IP of build
    add_host:
      hostname: "{{ item.public_dns_name }}"
      groupname: awsBuild
    loop: "{{ BuildInstance_result.instances }}"

  - name: Add EC2 Build as known hosts
    known_hosts:
      name: "{{ item.public_dns_name }}"
      key: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' + item.public_dns_name) }}"
    with_items: "{{ BuildInstance_result.instances }}"

  - name: Add public IP of prod
    add_host:
      hostname: "{{ item.public_dns_name }}"
      groupname: awsProd
    loop: "{{ ProdInstance_result.instances }}"

  - name: Add EC2 Build as known hosts
    known_hosts:
      name: "{{ item.public_dns_name }}"
      key: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' + item.public_dns_name) }}"
    with_items: "{{ ProdInstance_result.instances }}"
    
  - name: Creating a new bucket
    amazon.aws.s3_bucket:
      name: finalexambucket777
      state: present
      
-  name: Configure EC2 instance
   hosts: awsBuild
   remote_user: ubuntu
   become: yes
   become_user: root
   gather_facts: False

   tasks:
   - name: Ensure aws directory is created
     file:
       path: ~/.aws
       state: directory
       mode: 0755

   - name: Ensure that aws cred is copied
     copy:
       src: ~/.aws
       dest: ~/.aws
       
   - name: Update repo cache
     apt:
       update_cache: yes
   
   - name: Esure git and maven package is present
     apt:
       update_cache: yes
       name:
       - git
       - maven
       - default-jdk
       - python3-pip
       state: present
       
   - name: Install boto
     pip:
       name: boto3

   - name: Ensure git java is present
     git:
       repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
       dest: /tmp/box
 
   - name: Build java source code with maven
     command: mvn package -f /tmp/box
 
   - name: Copy artefact to bucket
     amazon.aws.aws_s3:
       bucket: finalexambucket777
       object: hello-1.0.war
       src: /tmp/box/target/hello-1.0.war
       mode: put
